### ndarray 다차원 배열 객체란? 
- np.array를 활용함

In [12]:
lst = [[1,2,3],[4,5,6]]
print(data[0])
print(lst[0][1:]) #중첩리스트 표현법

[1 2 3]
[2, 3]


In [10]:
import numpy as np
data = np.array( [[1,2,3],[4,5,6]] ) #중첩리스트
print(data[0])
print(data[0,1:])

[1 2 3]
[2 3]


### ndarray 활용 및 비교
- 합, 곱

In [6]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst3 = lst1 + lst2
print(lst3) #그냥 뒤에 붙여줌

[1, 2, 3, 4, 5, 6]


In [7]:
lst1 = np.array([1,2,3])
lst2 = np.array([4,5,6])
lst3 = lst1 + lst2
print(lst3) # ndarray는 요소간의 합으로 됨.

[5 7 9]


In [8]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst3 = lst1 * 3
print(lst3) #그냥 뒤에 붙여줌

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [9]:
lst1 = np.array([1,2,3])
lst2 = np.array([4,5,6])
lst3 = lst1 * 3 
print(lst3) # ndarray는 요소간의 합으로 됨.

[3 6 9]


### 왜 1D array를 shape(4,)라고 하나요? 

In [14]:
lst = [1]
print(lst) # 원소가 하나여도 리스트가 만들어짐 

tup = (1)
print(tup) # 스칼라가 되어버림

# 숫자값이 하나인 튜플을 만들고자하면 
tup = (1,) # 표기법을 다음과같이 해줘야함
print(tup)

[1]
1
(1,)


### 브로드캐스팅 이해
- 축을 잘 이해하자

In [19]:
data = np.array( [[1,2,3],[4,5,6]] )
print(data)
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
print(data.mean(0)) # 0번 축에대한 평균
print(data.mean(1)) # 1번 축에대한 평균

[2.5 3.5 4.5]
[2. 5.]


### 디멘젼의 의해

In [ ]:
(2,3) #3개의 속성을 2명이 가짐 
즉, 국어, 영어, 수학의 3개의 속성을 
A, B라는 사람이 가지고 있음 

### np.newaxis 축을 늘려보자

In [22]:
arr = np.zeros((4,4))
arr
print(arr.shape)

(4, 4)


In [29]:
arr_3d = arr[:, np.newaxis, :]  #가운데에 축을 늘림
print(arr_3d.shape)

(4, 1, 4)
