# 정규화
- 단위가 다른경우, 분포가 다른경우 사용
즉 상대적인 크기차이를 제거하고자 함.

In [13]:
import pandas as pd
import numpy as np
x = [10,1,2,3,4,1,2,3,2]
df = pd.DataFrame(x, columns = ['a'])
df

a
0  10
1   1
2   2
3   3
4   4
5   1
6   2
7   3
8   2

# minmax scaler  = 정규화 
- 모든 피쳐가 0~1사이에 있도록 데이터를 재조정함.
- 다만 이상치가 있는경우 매우 좁은 범위로 압축됨.

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler().fit(df).transform(df)
scaler1

array([[1.        ],
       [0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.        ],
       [0.11111111],
       [0.22222222],
       [0.11111111]])

# z-score = standard scaler = 표준화 
- 평균0 표준편차가 1이되도록 표준화하는 방법

In [16]:
from sklearn.preprocessing import StandardScaler
scaler2 = StandardScaler().fit(df).transform(df)
scaler2

array([[ 2.64850874],
       [-0.81163977],
       [-0.42717883],
       [-0.04271788],
       [ 0.34174306],
       [-0.81163977],
       [-0.42717883],
       [-0.04271788],
       [-0.42717883]])

# RobustScaler scaler 
- 중앙값과 IQR을 활용하여 표준화하는 방법

In [17]:
from sklearn.preprocessing import RobustScaler
scaler3 = RobustScaler().fit(df).transform(df)
scaler3

array([[ 8.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.]])